import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Link, useLocation } from 'wouter';
import { ArrowDown, ArrowUp, ImagePlus, Upload } from 'lucide-react';
import { BrandMark } from '@/components/brand/brand-mark';
import { Bars } from '@/components/admin/surveys/bars';
import { Button } from '@/components/ui/button';
import { Card, CardBody, CardHeader } from '@/components/ui/card';
import { Input, Textarea } from '@/components/ui/field';
import { formatAnswer } from '@/surveys/answers';
import { questionTypeLabels, type SurveyQuestion } from '@/surveys/types';
import { api } from '@/lib/opero-api';

const date = (value: string | null | undefined) => value ? new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const shortDate = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString() : '—';
const csv = (id: string) => `/api/opero/admin/surveys/${id}/export`;
const blankScene = { question: '', thinkingMs: 1200, answerTag: '', answerMain: '', answerSupport: '', chips: [] as string[], enabled: true };

export function Notice({ children, danger = false }: { children: ReactNode; danger?: boolean }) {
  return <div role="status" className={`rounded-lg border px-4 py-3 text-sm ${danger ? 'border-danger/40 bg-danger-soft text-danger' : 'border-success/40 bg-success-soft text-fg'}`}>{children}</div>;
}
export function Header({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) {
  return <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-fg-subtle">Opero / Admin</p><h1 className="text-display-sm font-medium text-metal">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm text-fg-muted">{description}</p>}</div>{actions}</header>;
}
export function Empty({ title, children }: { title: string; children: ReactNode }) {
  return <div className="rounded-xl border border-dashed border-line-strong px-6 py-12 text-center"><h2 className="font-semibold text-fg">{title}</h2><p className="mt-2 text-sm text-fg-muted">{children}</p></div>;
}
export function useData<T = any>(path: string) {
  const [data, setData] = useState<T | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const reload = () => { setLoading(true); setError(''); api<T>(path).then(setData).catch(e => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(() => { reload(); }, [path]);
  return { data, loading, error, reload };
}
export function State({ loading, error, retry, children }: { loading: boolean; error: string; retry: () => void; children: ReactNode }) {
  if (loading) return <div className="animate-pulse space-y-3">{[0, 1, 2].map(n => <div key={n} className="h-20 rounded-xl bg-surface-raised" />)}</div>;
  if (error) return <Notice danger>{error} <button className="ml-2 underline" onClick={retry}>Retry</button></Notice>;
  return <>{children}</>;
}
export function useAction(reload?: () => void) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
  const run = async (path: string, method: string, body?: unknown) => {
    setBusy(true); setError(''); setMessage('');
    try {
      const result = await api(path, { method, ...(body === undefined ? {} : { body: body instanceof FormData ? body : JSON.stringify(body) }) });
      setMessage('Changes saved.'); reload?.(); return { ok: true as const, data: result };
    } catch (e) { setError((e as Error).message); return { ok: false as const }; }
    finally { setBusy(false); }
  };
  return { busy, message, error, run };
}
export function Feedback({ action }: { action: ReturnType<typeof useAction> }) {
  return <>{action.error && <Notice danger>{action.error}</Notice>}{action.message && <Notice>{action.message}</Notice>}</>;
}
type MediaItem = { id: string; url: string; filename: string; contentType: string; size: number; width: number | null; height: number | null; createdAt: string; usedIn: string[] };
export function Media() {
  const q = useData<MediaItem[]>('/admin/media'), action = useAction(q.reload), [uploading, setUploading] = useState(false);
  const upload = async (file: File) => {
    const form = new FormData(); form.set('file', file); setUploading(true);
    await action.run('/admin/media', 'POST', form); setUploading(false);
  };
  return <div className="space-y-8"><Header title="Media" description="Images used across the site. Select an image to copy its URL." actions={<label className="inline-flex cursor-pointer items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-sm font-semibold text-on-accent"><Upload className="size-4" />{uploading ? 'Uploading…' : 'Upload image'}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" className="sr-only" disabled={uploading} onChange={e => { const file = e.target.files?.[0]; if (file) void upload(file); e.target.value = ''; }} /></label>} /><Feedback action={action} /><State {...q} retry={q.reload}>{q.data?.length ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{q.data.map(item => <Card key={item.id} className="overflow-hidden"><div className="media-thumb flex aspect-[4/3] items-center justify-center"><img src={item.url} alt={item.filename} loading="lazy" className="max-h-full max-w-full object-contain" /></div><CardBody className="space-y-3"><p className="truncate font-medium" title={item.filename}>{item.filename}</p><p className="text-xs text-fg-muted">{item.width && item.height ? `${item.width} × ${item.height} · ` : ''}{Math.round(item.size / 1024)} KB · {shortDate(item.createdAt)}</p>{item.usedIn.length ? <p className="text-xs text-fg-muted">Used in: {item.usedIn.join(', ')}</p> : <p className="text-xs text-fg-subtle">Not in use</p>}<div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" onClick={async () => { try { await navigator.clipboard.writeText(new URL(item.url, window.location.origin).href); } catch { window.prompt('Copy image URL', new URL(item.url, window.location.origin).href); } }}>Copy URL</Button><Button variant="danger" size="sm" disabled={action.busy || item.usedIn.length > 0} onClick={() => { if (window.confirm(`Delete ${item.filename}? This cannot be undone.`)) void action.run(`/admin/media/${item.id}`, 'DELETE'); }}>Delete</Button></div></CardBody></Card>)}</div> : <Empty title="No images yet"><ImagePlus className="mx-auto mb-3 size-8 text-fg-subtle" />Upload an image to use it in the site.</Empty>}</State></div>;
}
type Scene = typeof blankScene & { id: string; position: number };
function SceneForm({ scene, onDone, onCancel }: { scene?: Scene; onDone: (data: typeof blankScene) => Promise<void>; onCancel: () => void }) {
  const [values, setValues] = useState<typeof blankScene>(() => scene ? { question: scene.question, thinkingMs: scene.thinkingMs, answerTag: scene.answerTag, answerMain: scene.answerMain, answerSupport: scene.answerSupport, chips: scene.chips || [], enabled: scene.enabled } : blankScene);
  const set = (field: keyof typeof blankScene, value: any) => setValues(v => ({ ...v, [field]: value }));
  return <Card><CardHeader title={scene ? 'Edit scene' : 'Add a scene'} /><CardBody><form className="space-y-5" onSubmit={async e => { e.preventDefault(); await onDone({ ...values, chips: values.chips.map(c => c.trim()).filter(Boolean) }); }}><div className="grid gap-5 sm:grid-cols-[1fr_10rem]"><label className="block space-y-2 text-sm font-medium">Question<Input required maxLength={200} value={values.question} onChange={e => set('question', e.target.value)} /></label><label className="block space-y-2 text-sm font-medium">Thinking delay (ms)<Input type="number" min={200} max={6000} step={100} value={values.thinkingMs} onChange={e => set('thinkingMs', Number(e.target.value))} /></label></div><label className="block space-y-2 text-sm font-medium">Answer tag<Input maxLength={80} value={values.answerTag} onChange={e => set('answerTag', e.target.value)} /></label><label className="block space-y-2 text-sm font-medium">Main answer<Input required maxLength={120} value={values.answerMain} onChange={e => set('answerMain', e.target.value)} /></label><label className="block space-y-2 text-sm font-medium">Supporting line<Textarea rows={2} maxLength={240} value={values.answerSupport} onChange={e => set('answerSupport', e.target.value)} /></label><fieldset><legend className="mb-2 text-sm font-medium">Chips (up to four)</legend><div className="grid gap-3 sm:grid-cols-2">{[0, 1, 2, 3].map(i => <Input key={i} aria-label={`Chip ${i + 1}`} maxLength={60} value={values.chips[i] || ''} onChange={e => set('chips', Array.from({ length: 4 }, (_, n) => n === i ? e.target.value : values.chips[n] || ''))} />)}</div></fieldset><div className="flex gap-2"><Button type="submit">Save scene</Button><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button></div></form></CardBody></Card>;
}
export function Console() {
  const q = useData<Scene[]>('/admin/scenes'), action = useAction(q.reload), [editing, setEditing] = useState<Scene | 'new' | null>(null);
  return <div className="space-y-8">
    <Header title="Oppie console" description="The conversation scenes shown on the home page. Order and visibility take effect when saved." actions={<Button onClick={() => setEditing('new')}>Add scene</Button>} />
    <Feedback action={action} />
    <State {...q} retry={q.reload}>
      <div className="space-y-4">
        {q.data?.map((scene, i) => <Card key={scene.id}>
          <CardHeader title={`${i + 1}. ${scene.question}`} description={scene.enabled ? 'Visible on the site' : 'Hidden'} actions={<div className="flex gap-2">
            <button aria-label={`Move scene ${i + 1} up`} disabled={!i || action.busy} onClick={() => void action.run(`/admin/scenes/${scene.id}/move`, 'POST', { direction: 'up' })}><ArrowUp className="size-4" /></button>
            <button aria-label={`Move scene ${i + 1} down`} disabled={i === (q.data?.length || 0) - 1 || action.busy} onClick={() => void action.run(`/admin/scenes/${scene.id}/move`, 'POST', { direction: 'down' })}><ArrowDown className="size-4" /></button>
          </div>} />
          <CardBody className="space-y-3">
            <p className="text-xs uppercase tracking-wider text-fg-subtle">{scene.answerTag}</p><p className="text-xl font-medium">{scene.answerMain}</p><p className="text-sm text-fg-muted">{scene.answerSupport}</p><p className="text-xs text-fg-muted">{scene.chips.join(' · ')}</p>
            <div className="flex flex-wrap gap-2 pt-2">
              <Button size="sm" variant="secondary" onClick={() => setEditing(scene)}>Edit</Button>
              <Button size="sm" variant="secondary" disabled={action.busy} onClick={() => void action.run(`/admin/scenes/${scene.id}/enabled`, 'PATCH', { enabled: !scene.enabled })}>{scene.enabled ? 'Hide' : 'Show'}</Button>
              <Button size="sm" variant="danger" disabled={action.busy} onClick={() => { if (window.confirm(`Delete the scene “${scene.question}”?`)) void action.run(`/admin/scenes/${scene.id}`, 'DELETE'); }}>Delete</Button>
            </div>
          </CardBody>
        </Card>)}
        {!q.data?.length && <Empty title="No scenes yet">Add the first conversation for the console.</Empty>}
      </div>
      {editing && <SceneForm key={editing === 'new' ? 'new' : editing.id} scene={editing === 'new' ? undefined : editing} onCancel={() => setEditing(null)} onDone={async data => { const result = await action.run(editing === 'new' ? '/admin/scenes' : `/admin/scenes/${editing.id}`, editing === 'new' ? 'POST' : 'PUT', data); if (result.ok) setEditing(null); }} />}
    </State>
  </div>;
}
export function Team({ selfId }: { selfId: string }) {
  const q = useData<any>('/admin/team'), action = useAction(q.reload), [name, setName] = useState(''), [email, setEmail] = useState('');
  return <div className="space-y-8"><Header title="Team" description="People who can manage the site." /><Feedback action={action} /><State {...q} retry={q.reload}><Card><CardHeader title="Administrators" /><ul className="divide-y divide-line">{(q.data?.users || []).map((user: any) => <li key={user.id} className="flex flex-wrap items-center justify-between gap-3 px-6 py-4 text-sm"><div><strong>{user.name || user.email}</strong><span className="ml-2 text-fg-muted">{user.email}</span><p className="mt-1 text-xs text-fg-subtle">{user.disabledAt ? 'Removed' : `Last signed in ${date(user.lastLoginAt)}`}</p></div>{user.id !== selfId && !user.disabledAt && <Button variant="danger" size="sm" disabled={action.busy} onClick={() => { if (window.confirm(`Remove ${user.email} from the admin team? Their sessions will end.`)) void action.run(`/admin/team/${user.id}`, 'DELETE'); }}>Remove</Button>}</li>)}</ul></Card><Card><CardHeader title="Invite an admin" description="They receive a one-time link to create their account." /><CardBody><form className="grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end" onSubmit={async e => { e.preventDefault(); const r = await action.run('/admin/team/invites', 'POST', { name, email }); if (r.ok) { setName(''); setEmail(''); } }}><label className="space-y-2 text-sm font-medium">Name (optional)<Input value={name} maxLength={80} onChange={e => setName(e.target.value)} /></label><label className="space-y-2 text-sm font-medium">Email<Input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><Button type="submit" disabled={action.busy}>Send invitation</Button></form></CardBody></Card><Card><CardHeader title="Invitations" /><ul className="divide-y divide-line">{(q.data?.invites || []).map((invite: any) => <li key={invite.id} className="flex flex-wrap items-center justify-between gap-3 px-6 py-4 text-sm"><div><strong>{invite.name || invite.email}</strong><span className="ml-2 text-fg-muted">{invite.email}</span><p className="mt-1 text-xs text-fg-subtle">{invite.acceptedAt ? 'Accepted' : invite.revokedAt ? 'Revoked' : `Expires ${date(invite.expiresAt)}`}</p></div>{!invite.acceptedAt && !invite.revokedAt && <div className="flex gap-2"><Button size="sm" variant="secondary" disabled={action.busy} onClick={() => void action.run(`/admin/team/invites/${invite.id}/resend`, 'POST')}>Resend</Button><Button size="sm" variant="danger" disabled={action.busy} onClick={() => { if (window.confirm(`Revoke the invitation for ${invite.email}?`)) void action.run(`/admin/team/invites/${invite.id}`, 'DELETE'); }}>Revoke</Button></div>}</li>)}{!q.data?.invites?.length && <li className="px-6 py-5 text-sm text-fg-muted">No invitations yet.</li>}</ul></Card></State></div>;
}
export function Account({ user }: { user: any }) {
  const action = useAction(), [currentPassword, setCurrent] = useState(''), [newPassword, setNew] = useState(''), [confirmPassword, setConfirm] = useState('');
  return <div className="space-y-8"><Header title="My account" description="Your profile and security." /><Card><CardHeader title="Profile" /><CardBody className="space-y-3 text-sm"><p><span className="text-fg-muted">Name · </span>{user.name || '—'}</p><p><span className="text-fg-muted">Email · </span>{user.email}</p></CardBody></Card><Feedback action={action} /><Card><CardHeader title="Change password" description="Other signed-in sessions will be signed out when you change your password." /><CardBody><form className="max-w-md space-y-5" onSubmit={async e => { e.preventDefault(); if (newPassword !== confirmPassword) { window.alert('The passwords do not match.'); return; } const result = await action.run('/admin/account/password', 'POST', { currentPassword, newPassword, confirmPassword }); if (result.ok) { setCurrent(''); setNew(''); setConfirm(''); } }}><label className="block space-y-2 text-sm font-medium">Current password<Input type="password" autoComplete="current-password" required value={currentPassword} onChange={e => setCurrent(e.target.value)} /></label><label className="block space-y-2 text-sm font-medium">New password<Input type="password" autoComplete="new-password" required minLength={12} value={newPassword} onChange={e => setNew(e.target.value)} /></label><label className="block space-y-2 text-sm font-medium">Confirm new password<Input type="password" autoComplete="new-password" required value={confirmPassword} onChange={e => setConfirm(e.target.value)} /></label><Button type="submit" disabled={action.busy}>Change password</Button></form></CardBody></Card></div>;
}
export function AcceptInvite() {
  const token = new URLSearchParams(window.location.search).get('token') || '';
  const q = useData<any>(token ? `/accept-invite?token=${encodeURIComponent(token)}` : '/accept-invite');
  const action = useAction(), [, navigate] = useLocation();
  const [name, setName] = useState(''), [password, setPassword] = useState(''), [confirmPassword, setConfirm] = useState('');
  useEffect(() => { if (q.data?.name) setName(q.data.name); }, [q.data?.name]);
  return <main className="flex min-h-dvh items-center justify-center px-gutter py-16"><div className="w-full max-w-md"><BrandMark name="opero-small" on="auto" className="mx-auto h-10" /><div className="mt-10 space-y-6 rounded-2xl border border-line bg-surface p-8 shadow-lg"><div><h1 className="text-xl font-semibold">Join the Opero team</h1><p className="mt-2 text-sm text-fg-muted">Create your account to access the admin.</p></div><State {...q} retry={q.reload}>{q.data && <form className="space-y-5" onSubmit={async e => { e.preventDefault(); if (password !== confirmPassword) { window.alert('The passwords do not match.'); return; } const result = await action.run('/accept-invite', 'POST', { token, name, password, confirmPassword }); if (result.ok) navigate('/admin'); }}><Feedback action={action} /><p className="text-sm text-fg-muted">Email · {q.data.email}</p><label className="block space-y-2 text-sm font-medium">Your name<Input required value={name} maxLength={80} autoComplete="name" onChange={e => setName(e.target.value)} /></label><label className="block space-y-2 text-sm font-medium">Choose a password<Input type="password" required minLength={12} autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} /></label><label className="block space-y-2 text-sm font-medium">Confirm password<Input type="password" required autoComplete="new-password" value={confirmPassword} onChange={e => setConfirm(e.target.value)} /></label><Button className="w-full" size="lg" type="submit" disabled={action.busy}>Create account</Button></form>}</State></div></div></main>;
}
export function SurveyMail({ survey, reload }: { survey: any; reload: () => void }) {
  const action = useAction(reload);
  const [templates, setTemplates] = useState(() => ({
    inviteSubject: survey.inviteSubject || '', inviteMessage: survey.inviteMessage || '',
    reminderSubject: survey.reminderSubject || '', reminderMessage: survey.reminderMessage || '',
  }));
  const recipients = survey.recipients || [];
  const uninvited = recipients.filter((r: any) => !r.invitedAt && !r.completedAt).length;
  const waiting = recipients.filter((r: any) => r.invitedAt && !r.completedAt).length;
  const send = async (kind: 'invite' | 'remind', count: number) => {
    if (!window.confirm(`Send ${kind === 'invite' ? 'invitations' : 'reminders'} to ${count} ${count === 1 ? 'person' : 'people'}?`)) return;
    const result = await action.run(`/admin/surveys/${survey.id}/send`, 'POST', { kind });
    if (result.ok) window.alert(`${result.data?.logOnly ? 'Email delivery is not configured; messages were written to the server log. ' : ''}Sent: ${result.data?.sent ?? 0}. Failed: ${result.data?.failed ?? 0}. Skipped: ${result.data?.skipped ?? 0}.`);
  };
  return <div className="space-y-6"><Feedback action={action} /><Card><CardHeader title="Send survey" description="Each recipient gets their own personal link." /><CardBody className="space-y-5">{survey.status !== 'open' && <Notice danger>Open the survey before sending emails, so the links work.</Notice>}<div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-fg-muted"><strong className="text-fg">{uninvited}</strong> not invited yet</p><Button disabled={action.busy || survey.status !== 'open' || !uninvited} onClick={() => void send('invite', uninvited)}>Send invitations</Button></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4"><p className="text-sm text-fg-muted"><strong className="text-fg">{waiting}</strong> invited, not finished</p><Button variant="secondary" disabled={action.busy || survey.status !== 'open' || !waiting} onClick={() => void send('remind', waiting)}>Send reminders</Button></div></CardBody></Card><Card><CardHeader title="Email wording" description="Use {name} and {survey} in the subject or message. Each email includes a personal link." /><CardBody><form className="space-y-6" onSubmit={e => { e.preventDefault(); void action.run(`/admin/surveys/${survey.id}/email-templates`, 'PUT', templates); }}><div className="grid gap-6 md:grid-cols-2">{(['invite', 'reminder'] as const).map(kind => <fieldset key={kind} className="space-y-4"><legend className="mb-2 font-semibold">{kind === 'invite' ? 'Invitation' : 'Reminder'}</legend><label className="block space-y-2 text-sm font-medium">Subject<Input required maxLength={200} value={templates[`${kind}Subject`]} onChange={e => setTemplates(t => ({ ...t, [`${kind}Subject`]: e.target.value }))} /></label><label className="block space-y-2 text-sm font-medium">Message<Textarea required rows={6} maxLength={5000} value={templates[`${kind}Message`]} onChange={e => setTemplates(t => ({ ...t, [`${kind}Message`]: e.target.value }))} /></label><div className="rounded-lg border border-line bg-canvas-raised p-4 text-sm"><p className="mb-2 text-xs uppercase text-fg-subtle">Preview</p><strong>{templates[`${kind}Subject`].replaceAll('{name}', recipients[0]?.name || 'Alex').replaceAll('{survey}', survey.title)}</strong><p className="mt-2 whitespace-pre-line text-fg-muted">{templates[`${kind}Message`].replaceAll('{name}', recipients[0]?.name || 'Alex').replaceAll('{survey}', survey.title)}</p></div></fieldset>)}</div><Button disabled={action.busy} type="submit">Save email wording</Button></form></CardBody></Card></div>;
}
export function Responses({ survey, responseId, reload }: { survey: any; responseId?: string; reload: () => void }) {
  const [page, setPage] = useState(1);
  const q = useData<any>(`/admin/surveys/${survey.id}/responses${responseId ? `/${responseId}` : `?page=${page}`}`);
  const action = useAction(() => { q.reload(); reload(); });
  const title = (row: any) => survey.anonymous ? `Response ${row.id.slice(0, 8)}` : row.recipientName || row.recipientEmail || (row.source === 'open' ? 'Open link' : 'Respondent');
  const deleteOne = async (id: string) => {
    if (!window.confirm('Delete this response? It will be removed from results and the CSV. This cannot be undone.')) return;
    const result = await action.run(`/admin/surveys/${survey.id}/responses/${id}`, 'DELETE');
    if (result.ok) window.location.href = `/admin/surveys/${survey.id}/responses`;
  };
  return <div className="space-y-6"><Feedback action={action} /><State {...q} retry={q.reload}>{responseId && q.data ? <><Link href={`/admin/surveys/${survey.id}/responses`} className="text-sm text-fg-muted underline">← All responses</Link><Card><CardHeader title={title(q.data)} description={`Submitted ${survey.anonymous ? shortDate(q.data.submittedAt) : date(q.data.submittedAt)} · ${q.data.source === 'invite' ? 'Invitation' : 'Open link'}`} /><CardBody><dl className="divide-y divide-line">{(q.data.questions || []).map((question: SurveyQuestion, i: number) => <div key={question.id} className="grid gap-1 py-4 sm:grid-cols-[2fr_3fr] sm:gap-6"><dt className="text-sm text-fg-muted">{i + 1}. {question.prompt}</dt><dd className="whitespace-pre-line">{formatAnswer(question, q.data.answers?.[question.id]) || <em className="text-fg-subtle">No answer</em>}</dd></div>)}</dl></CardBody></Card><div className="flex items-center justify-between gap-4 rounded-xl border border-line p-5"><p className="text-sm text-fg-muted">Deleting this response removes it from reports. An invited person can then use their link again.</p><Button variant="danger" disabled={action.busy} onClick={() => void deleteOne(q.data.id)}>Delete response</Button></div></> : <><div className="flex justify-end">{q.data?.total ? <a href={csv(survey.id)} className="rounded-full border border-line-strong px-4 py-2 text-sm font-medium hover:bg-accent-soft">Download CSV</a> : null}</div>{q.data?.rows?.length ? <Card><ul className="divide-y divide-line">{q.data.rows.map((row: any) => <li key={row.id}><Link href={`/admin/surveys/${survey.id}/responses/${row.id}`} className="flex flex-wrap justify-between gap-3 px-6 py-4 hover:bg-accent-soft"><span><strong>{title(row)}</strong><span className="ml-2 text-xs text-fg-muted">{row.source === 'invite' ? 'Invitation' : 'Open link'}</span></span><span className="text-sm text-fg-muted">{survey.anonymous ? shortDate(row.submittedAt) : date(row.submittedAt)}</span></Link></li>)}</ul></Card> : <Empty title="No responses yet">Responses appear here as people submit the survey.</Empty>}{q.data?.pages > 1 && <nav className="flex items-center justify-between text-sm"><Button variant="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>Newer</Button><span>Page {page} of {q.data.pages}</span><Button variant="secondary" disabled={page >= q.data.pages} onClick={() => setPage(page + 1)}>Older</Button></nav>}</>}</State></div>;
}
export function Results({ survey }: { survey: any }) {
  const q = useData<any>(`/admin/surveys/${survey.id}/results`);
  return <div className="space-y-6"><State {...q} retry={q.reload}>{q.data && <><div className="flex flex-wrap items-end justify-between gap-4"><dl className="flex flex-wrap gap-8">{[['Responses', q.data.counts.responses], ['From invitations', q.data.counts.fromInvites], ['From the open link', q.data.counts.fromOpenLink], ['Invitations finished', `${q.data.counts.completed} of ${q.data.counts.invited}`]].map(([label, value]) => <div key={String(label)}><dt className="text-xs font-semibold uppercase tracking-widest text-fg-subtle">{label}</dt><dd className="mt-1 text-2xl font-semibold">{value}</dd></div>)}</dl>{q.data.counts.responses > 0 && <div className="flex gap-2"><Link href={`/admin/surveys/${survey.id}/responses`} className="rounded-full border border-line-strong px-4 py-2 text-sm">Individual responses</Link><a href={csv(survey.id)} className="rounded-full border border-line-strong px-4 py-2 text-sm">Download CSV</a></div>}</div>{q.data.counts.responses ? <><p className="text-sm text-fg-muted">Last response {survey.anonymous ? shortDate(q.data.lastResponseAt) : date(q.data.lastResponseAt)}. {survey.anonymous && 'Answers are not linked to people.'}</p><ol className="space-y-5">{q.data.questions.map(({ question, summary }: any, i: number) => <li key={question.id}><Card><CardHeader title={`${i + 1}. ${question.prompt}`} description={`${questionTypeLabels[question.type as keyof typeof questionTypeLabels]} · ${summary.answered} answers${summary.skipped ? ` · ${summary.skipped} skipped` : ''}`} /><CardBody>{!summary.answered ? <p className="text-sm text-fg-muted">Nobody has answered this question yet.</p> : summary.kind === 'text' ? <ul className="divide-y divide-line">{summary.answers.map((a: any) => <li key={a.responseId} className="py-3"><p className="whitespace-pre-line">{a.text}</p><Link href={`/admin/surveys/${survey.id}/responses/${a.responseId}`} className="mt-1 block text-xs text-fg-muted underline">{survey.anonymous ? shortDate(a.submittedAt) : `${a.respondent || 'Open link'} · ${date(a.submittedAt)}`}</Link></li>)}</ul> : <div className="space-y-4">{summary.kind === 'rating' && <p className="text-2xl font-semibold">{summary.average?.toFixed(1)} <span className="text-base font-normal text-fg-muted">average out of 5</span></p>}{summary.kind === 'nps' && <p className="text-2xl font-semibold">{summary.score > 0 ? '+' : ''}{summary.score} <span className="text-base font-normal text-fg-muted">Net Promoter Score · {summary.promoters} promoters · {summary.passives} passives · {summary.detractors} detractors</span></p>}{summary.multiple && <p className="text-sm text-fg-muted">People could choose more than one option.</p>}<Bars bars={summary.bars} /></div>}</CardBody></Card></li>)}</ol></> : <Empty title="No responses yet">Results will appear here as people respond.</Empty>}</>}</State></div>;
}
export function DeleteAllResponses({ survey, reload }: { survey: any; reload: () => void }) {
  const action = useAction(reload);
  const count = survey.counts?.responses || 0;
  return <Card><CardHeader title="Delete responses" description="For testing or starting over. This permanently removes every answer and resets completion for invitees." /><CardBody className="space-y-4"><Feedback action={action} /><p className="text-sm text-fg-muted">{count} {count === 1 ? 'response' : 'responses'} stored.</p><Button variant="danger" disabled={!count || action.busy} onClick={async () => { if (window.confirm(`Permanently delete all ${count} responses to “${survey.title}”? This cannot be undone.`)) { const result = await action.run(`/admin/surveys/${survey.id}/responses`, 'DELETE'); if (result.ok) window.alert(`${result.data.deleted} responses deleted.`); } }}>Delete all responses</Button></CardBody></Card>;
}