-- The company Opero was built inside is never named, as the owner asked: it is
-- the founder's former company, or our flagship operator (the Investor Hub's
-- cap table already calls it the Flagship operator, 0009). Rewords the copy
-- already saved, once: first the sentences the site shipped with, word for
-- word, then any other mention, capitalized at the start of a text or a
-- sentence. Published sections that change get a new version, so each can
-- still be rolled back; drafts change too, so publishing one does not bring
-- the name back, and so do the earlier versions, so rolling back to one does
-- not either. Then the settings, the Oppie console's scenes and the media
-- descriptions. Safe to run again: the second run finds nothing to change.
WITH updated AS (
  UPDATE "content_sections"
  SET "published" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("published"::text, 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi')::jsonb,
      "version" = "version" + 1,
      "published_at" = now(),
      "published_by" = NULL
  WHERE "published"::text ILIKE '%oxford%'
  RETURNING "id", "version", "published"
)
INSERT INTO "content_versions" ("section_id", "version", "data", "note")
SELECT "id", "version", "published", 'The flagship operator, never named' FROM updated;--> statement-breakpoint
-- Unpublished drafts.
UPDATE "content_sections"
SET "draft" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("draft"::text, 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi')::jsonb
WHERE "draft"::text ILIKE '%oxford%';--> statement-breakpoint
-- The earlier versions, so a rollback does not bring the name back.
UPDATE "content_versions"
SET "data" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("data"::text, 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi')::jsonb
WHERE "data"::text ILIKE '%oxford%';--> statement-breakpoint
-- The site's name, the program label, and the home page's search title and description.
UPDATE "site_settings"
SET "site_name" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("site_name", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi'),
    "partner_program_label" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("partner_program_label", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi'),
    "home_meta_title" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("home_meta_title", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi'),
    "home_meta_description" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("home_meta_description", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi')
WHERE concat_ws(' ', "site_name", "partner_program_label", "home_meta_title", "home_meta_description") ILIKE '%oxford%';--> statement-breakpoint
-- The Oppie console's scenes.
UPDATE "console_scenes"
SET "question" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("question", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi'),
    "answer_tag" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("answer_tag", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi'),
    "answer_main" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("answer_main", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi'),
    "answer_support" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("answer_support", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi'),
    "follow_up" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("follow_up", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi'),
    "chips" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("chips"::text, 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi')::text[],
    "answer_table" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("answer_table"::text, 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi')::jsonb
WHERE concat_ws(' ', "question", "answer_tag", "answer_main", "answer_support", "follow_up", "chips"::text, "answer_table"::text) ILIKE '%oxford%';--> statement-breakpoint
-- What the media library says each picture shows.
UPDATE "media"
SET "alt" = regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(replace(replace(replace(replace(replace("alt", 'Opero was built inside Oxford Companies, a commercial and residential property management firm in Ann Arbor, where', 'Opero was built inside the founder''s former company, a commercial and residential property management firm, where'), 'It runs Oxford Companies, a commercial and residential property management firm in Ann Arbor, every day', 'It runs our flagship operator, a commercial and residential property management firm, every day'), 'What runs at Oxford today, and what''s on deck.', 'What runs today, and what''s on deck.'), 'Running at Oxford today', 'Running today'), 'Oxford Companies, a commercial and residential property management firm in Ann Arbor', 'our flagship operator, a commercial and residential property management firm'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies'(?!s)$$, $$\1Our flagship operator's$$, 'gi'), $$[[:<:]]Oxford Companies'(?!s)$$, $$our flagship operator's$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford Companies$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford Companies[[:>:]]$$, $$our flagship operator$$, 'gi'), $$(^|"|\\n|[.!?][[:space:]]+)Oxford[[:>:]]$$, $$\1Our flagship operator$$, 'gi'), $$[[:<:]]Oxford[[:>:]]$$, $$our flagship operator$$, 'gi')
WHERE "alt" ILIKE '%oxford%';--> statement-breakpoint
-- Tells every running server to reload the public content.
UPDATE "site_state" SET "content_version" = "content_version" + 1;
